sudo: required

language: node_js
node_js:
  - 13.1.0

before_script:
- openssl aes-256-cbc -K $encrypted_a41e61b5234a_key -iv $encrypted_a41e61b5234a_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
  - npm i

stages:
  - name: Build
  - name: TestCoverage
  
  - name: DeployKaraoke
    if: branch = master AND type=push
    
  - name: DeployKaraokeTest
    if: branch = cicd AND type=push

jobs:
  include:
    - stage: Build
      script:
        - npm run build
        - ssh -q -p 22 ${USER}@${HOST} "/bin/mkdir -p /home/${USER}/build/karaoke-backend"
        - rsync -a -e "ssh -p 22" ./ ${USER}@${HOST}:/home/${USER}/build/karaoke-backend/ --delete --exclude="node_modules"

    - stage: TestCoverage
      script:
        - npm run test:ci

    - stage: DeployKaraokeTest
      script:
        - ssh -q -p 22 ${USER}@${HOST} "/home/${USER}/pm2/backend_karaoke_test/start.sh"

    - stage: DeployKaraoke
      script:
        - ssh -q -p 22 ${USER}@${HOST} "/home/${USER}/pm2/backend_karaoke/start.sh"