language: node_js
node_js:
  - 13.1.0
 
install:
  - npm i
  
stages:
  - Build
  - TestCoverage

jobs:
  include:
    - stage: Build
      script:
        - npm run build
    - stage: TestCoverage
      script:
        - npm run test:ci
