language: node_js
node_js:
  - 11
 
install:
  - npm i
  
stages:
  - UnitTest
  
jobs:
  include:
    - stage: Unit Tests
      script:
        - npm run test
    - stage: Test Coverage
      script:
        - npm run test:ci
